name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: make rego-playground-container

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Set up nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Make ui-lint
      run: make ui-lint

    - name: Make
      run: make all

    - name: Setup Regal
      uses: StyraInc/setup-regal@main
      with:
        version: latest

    - name: Regal Lint
      run: regal lint --format=github policy-catalog
